services:
  - type: web
    name: math-focused-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
